/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExpenseCategory = { 'other' : null } |
  { 'marketing' : null } |
  { 'supplies' : null } |
  { 'rent' : null } |
  { 'utilities' : null } |
  { 'maintenance' : null } |
  { 'payroll' : null } |
  { 'foodCost' : null };
export interface ExpenseEntry {
  'id' : bigint,
  'expenseType' : ExpenseType,
  'paymentMethod' : PaymentMethod,
  'date' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : [] | [string],
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseType = { 'fixed' : null } |
  { 'variable' : null };
export interface InventoryItem {
  'id' : bigint,
  'lowStockThreshold' : [] | [number],
  'name' : string,
  'createdAt' : Time,
  'unit' : string,
  'updatedAt' : Time,
}
export type PaymentMethod = { 'creditCard' : null } |
  { 'other' : null } |
  { 'bank' : null } |
  { 'cash' : null };
export interface PettyCashTransaction {
  'id' : bigint,
  'transactionType' : { 'out' : null } |
    { 'cashIn' : null },
  'createdAt' : Time,
  'updatedAt' : Time,
  'amount' : number,
  'dateTime' : Time,
  'reason' : string,
}
export interface SalesEntry {
  'id' : bigint,
  'date' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : [] | [string],
  'amount' : number,
}
export interface StockMovement {
  'id' : bigint,
  'itemId' : bigint,
  'createdAt' : Time,
  'movementType' : { 'out' : null } |
    { 'adjustment' : null } |
    { 'stockIn' : null },
  'updatedAt' : Time,
  'notes' : [] | [string],
  'quantity' : number,
  'dateTime' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addInventoryItem' : ActorMethod<
    [string, string, [] | [number]],
    InventoryItem
  >,
  'addPettyCashTransaction' : ActorMethod<
    [{ 'out' : null } | { 'cashIn' : null }, number, string],
    PettyCashTransaction
  >,
  'addStockMovement' : ActorMethod<
    [
      bigint,
      { 'out' : null } |
        { 'adjustment' : null } |
        { 'stockIn' : null },
      number,
      [] | [string],
    ],
    StockMovement
  >,
  'createExpenseEntry' : ActorMethod<
    [
      bigint,
      ExpenseCategory,
      ExpenseType,
      number,
      PaymentMethod,
      [] | [string],
    ],
    ExpenseEntry
  >,
  'createSalesEntry' : ActorMethod<[bigint, number, [] | [string]], SalesEntry>,
  'deleteExpenseEntry' : ActorMethod<[bigint], undefined>,
  'deleteSalesEntry' : ActorMethod<[bigint], undefined>,
  'getAllExpenseEntries' : ActorMethod<[], Array<ExpenseEntry>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllPettyCashTransactions' : ActorMethod<[], Array<PettyCashTransaction>>,
  'getAllSalesEntries' : ActorMethod<[], Array<SalesEntry>>,
  'getAllStockMovements' : ActorMethod<[], Array<StockMovement>>,
  'getExpenseEntry' : ActorMethod<[bigint], ExpenseEntry>,
  'getProfitAndLoss' : ActorMethod<
    [bigint, bigint],
    {
      'totalExpenses' : number,
      'totalSales' : number,
      'netProfitLoss' : number,
    }
  >,
  'getSalesEntry' : ActorMethod<[bigint], SalesEntry>,
  'updateExpenseEntry' : ActorMethod<
    [
      bigint,
      bigint,
      ExpenseCategory,
      ExpenseType,
      number,
      PaymentMethod,
      [] | [string],
    ],
    ExpenseEntry
  >,
  'updateSalesEntry' : ActorMethod<
    [bigint, bigint, number, [] | [string]],
    SalesEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];