/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const InventoryItem = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Opt(IDL.Float64),
  'name' : IDL.Text,
  'createdAt' : Time,
  'unit' : IDL.Text,
  'updatedAt' : Time,
});
export const PettyCashTransaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Variant({ 'out' : IDL.Null, 'cashIn' : IDL.Null }),
  'createdAt' : Time,
  'updatedAt' : Time,
  'amount' : IDL.Float64,
  'dateTime' : Time,
  'reason' : IDL.Text,
});
export const StockMovement = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'createdAt' : Time,
  'movementType' : IDL.Variant({
    'out' : IDL.Null,
    'adjustment' : IDL.Null,
    'stockIn' : IDL.Null,
  }),
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Float64,
  'dateTime' : Time,
});
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'supplies' : IDL.Null,
  'rent' : IDL.Null,
  'utilities' : IDL.Null,
  'maintenance' : IDL.Null,
  'payroll' : IDL.Null,
  'foodCost' : IDL.Null,
});
export const ExpenseType = IDL.Variant({
  'fixed' : IDL.Null,
  'variable' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'creditCard' : IDL.Null,
  'other' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
});
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'expenseType' : ExpenseType,
  'paymentMethod' : PaymentMethod,
  'date' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const SalesEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
      [InventoryItem],
      [],
    ),
  'addPettyCashTransaction' : IDL.Func(
      [
        IDL.Variant({ 'out' : IDL.Null, 'cashIn' : IDL.Null }),
        IDL.Float64,
        IDL.Text,
      ],
      [PettyCashTransaction],
      [],
    ),
  'addStockMovement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'out' : IDL.Null,
          'adjustment' : IDL.Null,
          'stockIn' : IDL.Null,
        }),
        IDL.Float64,
        IDL.Opt(IDL.Text),
      ],
      [StockMovement],
      [],
    ),
  'createExpenseEntry' : IDL.Func(
      [
        IDL.Nat,
        ExpenseCategory,
        ExpenseType,
        IDL.Float64,
        PaymentMethod,
        IDL.Opt(IDL.Text),
      ],
      [ExpenseEntry],
      [],
    ),
  'createSalesEntry' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
      [SalesEntry],
      [],
    ),
  'deleteExpenseEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSalesEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllPettyCashTransactions' : IDL.Func(
      [],
      [IDL.Vec(PettyCashTransaction)],
      ['query'],
    ),
  'getAllSalesEntries' : IDL.Func([], [IDL.Vec(SalesEntry)], ['query']),
  'getAllStockMovements' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
  'getExpenseEntry' : IDL.Func([IDL.Nat], [ExpenseEntry], ['query']),
  'getProfitAndLoss' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'totalExpenses' : IDL.Float64,
          'totalSales' : IDL.Float64,
          'netProfitLoss' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getSalesEntry' : IDL.Func([IDL.Nat], [SalesEntry], ['query']),
  'updateExpenseEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        ExpenseCategory,
        ExpenseType,
        IDL.Float64,
        PaymentMethod,
        IDL.Opt(IDL.Text),
      ],
      [ExpenseEntry],
      [],
    ),
  'updateSalesEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
      [SalesEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const InventoryItem = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Opt(IDL.Float64),
    'name' : IDL.Text,
    'createdAt' : Time,
    'unit' : IDL.Text,
    'updatedAt' : Time,
  });
  const PettyCashTransaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Variant({ 'out' : IDL.Null, 'cashIn' : IDL.Null }),
    'createdAt' : Time,
    'updatedAt' : Time,
    'amount' : IDL.Float64,
    'dateTime' : Time,
    'reason' : IDL.Text,
  });
  const StockMovement = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'createdAt' : Time,
    'movementType' : IDL.Variant({
      'out' : IDL.Null,
      'adjustment' : IDL.Null,
      'stockIn' : IDL.Null,
    }),
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Float64,
    'dateTime' : Time,
  });
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'supplies' : IDL.Null,
    'rent' : IDL.Null,
    'utilities' : IDL.Null,
    'maintenance' : IDL.Null,
    'payroll' : IDL.Null,
    'foodCost' : IDL.Null,
  });
  const ExpenseType = IDL.Variant({
    'fixed' : IDL.Null,
    'variable' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'creditCard' : IDL.Null,
    'other' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
  });
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'expenseType' : ExpenseType,
    'paymentMethod' : PaymentMethod,
    'date' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const SalesEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Float64)],
        [InventoryItem],
        [],
      ),
    'addPettyCashTransaction' : IDL.Func(
        [
          IDL.Variant({ 'out' : IDL.Null, 'cashIn' : IDL.Null }),
          IDL.Float64,
          IDL.Text,
        ],
        [PettyCashTransaction],
        [],
      ),
    'addStockMovement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'out' : IDL.Null,
            'adjustment' : IDL.Null,
            'stockIn' : IDL.Null,
          }),
          IDL.Float64,
          IDL.Opt(IDL.Text),
        ],
        [StockMovement],
        [],
      ),
    'createExpenseEntry' : IDL.Func(
        [
          IDL.Nat,
          ExpenseCategory,
          ExpenseType,
          IDL.Float64,
          PaymentMethod,
          IDL.Opt(IDL.Text),
        ],
        [ExpenseEntry],
        [],
      ),
    'createSalesEntry' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
        [SalesEntry],
        [],
      ),
    'deleteExpenseEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSalesEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllExpenseEntries' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllPettyCashTransactions' : IDL.Func(
        [],
        [IDL.Vec(PettyCashTransaction)],
        ['query'],
      ),
    'getAllSalesEntries' : IDL.Func([], [IDL.Vec(SalesEntry)], ['query']),
    'getAllStockMovements' : IDL.Func([], [IDL.Vec(StockMovement)], ['query']),
    'getExpenseEntry' : IDL.Func([IDL.Nat], [ExpenseEntry], ['query']),
    'getProfitAndLoss' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'totalExpenses' : IDL.Float64,
            'totalSales' : IDL.Float64,
            'netProfitLoss' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getSalesEntry' : IDL.Func([IDL.Nat], [SalesEntry], ['query']),
    'updateExpenseEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          ExpenseCategory,
          ExpenseType,
          IDL.Float64,
          PaymentMethod,
          IDL.Opt(IDL.Text),
        ],
        [ExpenseEntry],
        [],
      ),
    'updateSalesEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Float64, IDL.Opt(IDL.Text)],
        [SalesEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };