/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    id: bigint;
    lowStockThreshold?: number;
    name: string;
    createdAt: Time;
    unit: string;
    updatedAt: Time;
}
export interface SalesEntry {
    id: bigint;
    date: bigint;
    createdAt: Time;
    updatedAt: Time;
    notes?: string;
    amount: number;
}
export type Time = bigint;
export interface PettyCashTransaction {
    id: bigint;
    transactionType: Variant_out_cashIn;
    createdAt: Time;
    updatedAt: Time;
    amount: number;
    dateTime: Time;
    reason: string;
}
export interface ExpenseEntry {
    id: bigint;
    expenseType: ExpenseType;
    paymentMethod: PaymentMethod;
    date: bigint;
    createdAt: Time;
    updatedAt: Time;
    notes?: string;
    category: ExpenseCategory;
    amount: number;
}
export interface StockMovement {
    id: bigint;
    itemId: bigint;
    createdAt: Time;
    movementType: Variant_out_adjustment_stockIn;
    updatedAt: Time;
    notes?: string;
    quantity: number;
    dateTime: Time;
}
export enum ExpenseCategory {
    other = "other",
    marketing = "marketing",
    supplies = "supplies",
    rent = "rent",
    utilities = "utilities",
    maintenance = "maintenance",
    payroll = "payroll",
    foodCost = "foodCost"
}
export enum ExpenseType {
    fixed = "fixed",
    variable = "variable"
}
export enum PaymentMethod {
    creditCard = "creditCard",
    other = "other",
    bank = "bank",
    cash = "cash"
}
export enum Variant_out_adjustment_stockIn {
    out = "out",
    adjustment = "adjustment",
    stockIn = "stockIn"
}
export enum Variant_out_cashIn {
    out = "out",
    cashIn = "cashIn"
}
export interface backendInterface {
    addInventoryItem(name: string, unit: string, lowStockThreshold: number | null): Promise<InventoryItem>;
    addPettyCashTransaction(transactionType: Variant_out_cashIn, amount: number, reason: string): Promise<PettyCashTransaction>;
    addStockMovement(itemId: bigint, movementType: Variant_out_adjustment_stockIn, quantity: number, notes: string | null): Promise<StockMovement>;
    createExpenseEntry(date: bigint, category: ExpenseCategory, expenseType: ExpenseType, amount: number, paymentMethod: PaymentMethod, notes: string | null): Promise<ExpenseEntry>;
    createSalesEntry(date: bigint, amount: number, notes: string | null): Promise<SalesEntry>;
    deleteExpenseEntry(id: bigint): Promise<void>;
    deleteSalesEntry(id: bigint): Promise<void>;
    getAllExpenseEntries(): Promise<Array<ExpenseEntry>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllPettyCashTransactions(): Promise<Array<PettyCashTransaction>>;
    getAllSalesEntries(): Promise<Array<SalesEntry>>;
    getAllStockMovements(): Promise<Array<StockMovement>>;
    getExpenseEntry(id: bigint): Promise<ExpenseEntry>;
    getProfitAndLoss(_startDate: bigint, _endDate: bigint): Promise<{
        totalExpenses: number;
        totalSales: number;
        netProfitLoss: number;
    }>;
    getSalesEntry(id: bigint): Promise<SalesEntry>;
    updateExpenseEntry(id: bigint, date: bigint, category: ExpenseCategory, expenseType: ExpenseType, amount: number, paymentMethod: PaymentMethod, notes: string | null): Promise<ExpenseEntry>;
    updateSalesEntry(id: bigint, date: bigint, amount: number, notes: string | null): Promise<SalesEntry>;
}
import type { ExpenseCategory as _ExpenseCategory, ExpenseEntry as _ExpenseEntry, ExpenseType as _ExpenseType, InventoryItem as _InventoryItem, PaymentMethod as _PaymentMethod, PettyCashTransaction as _PettyCashTransaction, SalesEntry as _SalesEntry, StockMovement as _StockMovement, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInventoryItem(arg0: string, arg1: string, arg2: number | null): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_InventoryItem_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_InventoryItem_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPettyCashTransaction(arg0: Variant_out_cashIn, arg1: number, arg2: string): Promise<PettyCashTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.addPettyCashTransaction(to_candid_variant_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PettyCashTransaction_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPettyCashTransaction(to_candid_variant_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PettyCashTransaction_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStockMovement(arg0: bigint, arg1: Variant_out_adjustment_stockIn, arg2: number, arg3: string | null): Promise<StockMovement> {
        if (this.processError) {
            try {
                const result = await this.actor.addStockMovement(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return from_candid_StockMovement_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStockMovement(arg0, to_candid_variant_n9(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return from_candid_StockMovement_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createExpenseEntry(arg0: bigint, arg1: ExpenseCategory, arg2: ExpenseType, arg3: number, arg4: PaymentMethod, arg5: string | null): Promise<ExpenseEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpenseEntry(arg0, to_candid_ExpenseCategory_n15(this._uploadFile, this._downloadFile, arg1), to_candid_ExpenseType_n17(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpenseEntry(arg0, to_candid_ExpenseCategory_n15(this._uploadFile, this._downloadFile, arg1), to_candid_ExpenseType_n17(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSalesEntry(arg0: bigint, arg1: number, arg2: string | null): Promise<SalesEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createSalesEntry(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSalesEntry(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExpenseEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpenseEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpenseEntry(arg0);
            return result;
        }
    }
    async deleteSalesEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSalesEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSalesEntry(arg0);
            return result;
        }
    }
    async getAllExpenseEntries(): Promise<Array<ExpenseEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenseEntries();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenseEntries();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPettyCashTransactions(): Promise<Array<PettyCashTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPettyCashTransactions();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPettyCashTransactions();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSalesEntries(): Promise<Array<SalesEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSalesEntries();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSalesEntries();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStockMovements(): Promise<Array<StockMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStockMovements();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStockMovements();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenseEntry(arg0: bigint): Promise<ExpenseEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenseEntry(arg0);
                return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenseEntry(arg0);
            return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfitAndLoss(arg0: bigint, arg1: bigint): Promise<{
        totalExpenses: number;
        totalSales: number;
        netProfitLoss: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitAndLoss(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitAndLoss(arg0, arg1);
            return result;
        }
    }
    async getSalesEntry(arg0: bigint): Promise<SalesEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesEntry(arg0);
                return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesEntry(arg0);
            return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateExpenseEntry(arg0: bigint, arg1: bigint, arg2: ExpenseCategory, arg3: ExpenseType, arg4: number, arg5: PaymentMethod, arg6: string | null): Promise<ExpenseEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpenseEntry(arg0, arg1, to_candid_ExpenseCategory_n15(this._uploadFile, this._downloadFile, arg2), to_candid_ExpenseType_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
                return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpenseEntry(arg0, arg1, to_candid_ExpenseCategory_n15(this._uploadFile, this._downloadFile, arg2), to_candid_ExpenseType_n17(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_PaymentMethod_n19(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
            return from_candid_ExpenseEntry_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSalesEntry(arg0: bigint, arg1: bigint, arg2: number, arg3: string | null): Promise<SalesEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesEntry(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
                return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesEntry(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3));
            return from_candid_SalesEntry_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ExpenseCategory_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseEntry_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseEntry): ExpenseEntry {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseType): ExpenseType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PettyCashTransaction_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PettyCashTransaction): PettyCashTransaction {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SalesEntry_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesEntry): SalesEntry {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StockMovement_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockMovement): StockMovement {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    itemId: bigint;
    createdAt: _Time;
    movementType: {
        out: null;
    } | {
        adjustment: null;
    } | {
        stockIn: null;
    };
    updatedAt: _Time;
    notes: [] | [string];
    quantity: number;
    dateTime: _Time;
}): {
    id: bigint;
    itemId: bigint;
    createdAt: Time;
    movementType: Variant_out_adjustment_stockIn;
    updatedAt: Time;
    notes?: string;
    quantity: number;
    dateTime: Time;
} {
    return {
        id: value.id,
        itemId: value.itemId,
        createdAt: value.createdAt,
        movementType: from_candid_variant_n13(_uploadFile, _downloadFile, value.movementType),
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        dateTime: value.dateTime
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseType: _ExpenseType;
    paymentMethod: _PaymentMethod;
    date: bigint;
    createdAt: _Time;
    updatedAt: _Time;
    notes: [] | [string];
    category: _ExpenseCategory;
    amount: number;
}): {
    id: bigint;
    expenseType: ExpenseType;
    paymentMethod: PaymentMethod;
    date: bigint;
    createdAt: Time;
    updatedAt: Time;
    notes?: string;
    category: ExpenseCategory;
    amount: number;
} {
    return {
        id: value.id,
        expenseType: from_candid_ExpenseType_n23(_uploadFile, _downloadFile, value.expenseType),
        paymentMethod: from_candid_PaymentMethod_n25(_uploadFile, _downloadFile, value.paymentMethod),
        date: value.date,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_ExpenseCategory_n27(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lowStockThreshold: [] | [number];
    name: string;
    createdAt: _Time;
    unit: string;
    updatedAt: _Time;
}): {
    id: bigint;
    lowStockThreshold?: number;
    name: string;
    createdAt: Time;
    unit: string;
    updatedAt: Time;
} {
    return {
        id: value.id,
        lowStockThreshold: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lowStockThreshold)),
        name: value.name,
        createdAt: value.createdAt,
        unit: value.unit,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: bigint;
    createdAt: _Time;
    updatedAt: _Time;
    notes: [] | [string];
    amount: number;
}): {
    id: bigint;
    date: bigint;
    createdAt: Time;
    updatedAt: Time;
    notes?: string;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.notes)),
        amount: value.amount
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    transactionType: {
        out: null;
    } | {
        cashIn: null;
    };
    createdAt: _Time;
    updatedAt: _Time;
    amount: number;
    dateTime: _Time;
    reason: string;
}): {
    id: bigint;
    transactionType: Variant_out_cashIn;
    createdAt: Time;
    updatedAt: Time;
    amount: number;
    dateTime: Time;
    reason: string;
} {
    return {
        id: value.id,
        transactionType: from_candid_variant_n8(_uploadFile, _downloadFile, value.transactionType),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        amount: value.amount,
        dateTime: value.dateTime,
        reason: value.reason
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    out: null;
} | {
    adjustment: null;
} | {
    stockIn: null;
}): Variant_out_adjustment_stockIn {
    return "out" in value ? Variant_out_adjustment_stockIn.out : "adjustment" in value ? Variant_out_adjustment_stockIn.adjustment : "stockIn" in value ? Variant_out_adjustment_stockIn.stockIn : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fixed: null;
} | {
    variable: null;
}): ExpenseType {
    return "fixed" in value ? ExpenseType.fixed : "variable" in value ? ExpenseType.variable : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creditCard: null;
} | {
    other: null;
} | {
    bank: null;
} | {
    cash: null;
}): PaymentMethod {
    return "creditCard" in value ? PaymentMethod.creditCard : "other" in value ? PaymentMethod.other : "bank" in value ? PaymentMethod.bank : "cash" in value ? PaymentMethod.cash : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    marketing: null;
} | {
    supplies: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    maintenance: null;
} | {
    payroll: null;
} | {
    foodCost: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "marketing" in value ? ExpenseCategory.marketing : "supplies" in value ? ExpenseCategory.supplies : "rent" in value ? ExpenseCategory.rent : "utilities" in value ? ExpenseCategory.utilities : "maintenance" in value ? ExpenseCategory.maintenance : "payroll" in value ? ExpenseCategory.payroll : "foodCost" in value ? ExpenseCategory.foodCost : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    out: null;
} | {
    cashIn: null;
}): Variant_out_cashIn {
    return "out" in value ? Variant_out_cashIn.out : "cashIn" in value ? Variant_out_cashIn.cashIn : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExpenseEntry>): Array<ExpenseEntry> {
    return value.map((x)=>from_candid_ExpenseEntry_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PettyCashTransaction>): Array<PettyCashTransaction> {
    return value.map((x)=>from_candid_PettyCashTransaction_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesEntry>): Array<SalesEntry> {
    return value.map((x)=>from_candid_SalesEntry_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockMovement>): Array<StockMovement> {
    return value.map((x)=>from_candid_StockMovement_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_ExpenseType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): _ExpenseType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    marketing: null;
} | {
    supplies: null;
} | {
    rent: null;
} | {
    utilities: null;
} | {
    maintenance: null;
} | {
    payroll: null;
} | {
    foodCost: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.marketing ? {
        marketing: null
    } : value == ExpenseCategory.supplies ? {
        supplies: null
    } : value == ExpenseCategory.rent ? {
        rent: null
    } : value == ExpenseCategory.utilities ? {
        utilities: null
    } : value == ExpenseCategory.maintenance ? {
        maintenance: null
    } : value == ExpenseCategory.payroll ? {
        payroll: null
    } : value == ExpenseCategory.foodCost ? {
        foodCost: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseType): {
    fixed: null;
} | {
    variable: null;
} {
    return value == ExpenseType.fixed ? {
        fixed: null
    } : value == ExpenseType.variable ? {
        variable: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    creditCard: null;
} | {
    other: null;
} | {
    bank: null;
} | {
    cash: null;
} {
    return value == PaymentMethod.creditCard ? {
        creditCard: null
    } : value == PaymentMethod.other ? {
        other: null
    } : value == PaymentMethod.bank ? {
        bank: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_out_cashIn): {
    out: null;
} | {
    cashIn: null;
} {
    return value == Variant_out_cashIn.out ? {
        out: null
    } : value == Variant_out_cashIn.cashIn ? {
        cashIn: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_out_adjustment_stockIn): {
    out: null;
} | {
    adjustment: null;
} | {
    stockIn: null;
} {
    return value == Variant_out_adjustment_stockIn.out ? {
        out: null
    } : value == Variant_out_adjustment_stockIn.adjustment ? {
        adjustment: null
    } : value == Variant_out_adjustment_stockIn.stockIn ? {
        stockIn: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
